### ISSUE TITLE
10.2.0 crashing IC2

### ISSUE THREAD

**Issue by Krougal** [Railcraft/Railcraft#1353]
Crash coming from IC2, obsidian dust recipe conflict. Haven't been able to find any info. Although the crash comes from IC2, disabling Railcraft stops it. I'd wager it's the IC2 API in RC vs IC2.
[crash-2017-11-03_20.02.59-client.txt](https://github.com/Railcraft/Railcraft/files/1442761/crash-2017-11-03_20.02.59-client.txt)
I tried replacing the API in the RC jar myself but no go.
Removing the API folder outright doesn't do it either :(
[crash-2017-11-03_20.11.28-client.txt](https://github.com/Railcraft/Railcraft/files/1442762/crash-2017-11-03_20.11.28-client.txt)

**Comment by liach** [comment]
@Generalcamo Did you add that recipe via ic2?

**Comment by ghost** [comment]
This can be temporarily worked around by going to railcraft.cfg and editing:
            B:obsidian=true
to
            B:obsidian=false

**Comment by Chocohead** [comment]
The issue lies from https://github.com/Railcraft/Railcraft/blob/mc-1.10.2/src/main/java/mods/railcraft/common/modules/ModuleResources.java#L134-L135

It adds in the recipes in pre-init, thus when IC2 adds it's own recipes in init there is a conflict and because IC2 doesn't try to override recipes, it crashes. If the Railcraft recipes are added in init or post-init (or generally after IC2 adds it's own), then it can set the replace option in `addRecipe` ([here](https://github.com/Railcraft/Railcraft/blob/mc-1.10.2/src/main/java/mods/railcraft/common/plugins/ic2/IC2Plugin.java#L148)) to true, which should allow the original goal.

**Comment by liach** [comment]
fix'd.
