### ISSUE TITLE
Steam texture bug 1.7.10

### ISSUE THREAD

**Issue by Samino2** [Railcraft/Railcraft#1381]
chisel turn the steam texture in missing texture ^^

**Comment by liach** [comment]
Take a look at #1367. Can you download both mods' latest versions from curseforge? 
Chisel: https://minecraft.curseforge.com/projects/chisel/files/2287442/download
Railcraft: https://minecraft.curseforge.com/projects/railcraft/files/2458987/download
Create a new world and see if the bug is still there.

**Comment by Samino2** [comment]
nope, don't working

**Comment by liach** [comment]
@Samino2 Screenshot, turn on F3

**Comment by Samino2** [comment]
its working, I have just restart my PC ^^

**Comment by liach** [comment]
haha. I will close then :smile: glad to see it fixed!
