### ISSUE TITLE
fix botania's use of rc api

### ISSUE THREAD

**Issue by liach** [Railcraft/Railcraft#1398]

**Comment by Amelia-** [comment]
Is the following error caused by this problem?
> net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: vazkii/botania/common/item/ItemPoolMinecart
...
Caused by: java.lang.NoClassDefFoundError: vazkii/botania/common/item/ItemPoolMinecart
...
Caused by: java.lang.ClassNotFoundException: vazkii.botania.common.item.ItemPoolMinecart
...
Caused by: java.lang.NoClassDefFoundError: mods/railcraft/api/core/items/IMinecartItem
...
Caused by: java.lang.ClassNotFoundException: mods.railcraft.api.core.items.IMinecartItem

**Comment by liach** [comment]
exactly, but i need to stablize rc api first.

**Comment by Amelia-** [comment]
This still doesn't seem to work. Perhaps I am doing something wrong?

I place Botania and Baubles in the /run/mods folder and then execute ./gradlew runClient. The resulting crash report has the same error as before.

This was with the latest version of the indev-1.12.2 branch.
I am using Botania r1.10-354 and Baubles 1.5.2.

**Comment by liach** [comment]
It should not. Botania should be shipping that class, or botania fails to strip that annotation. I will ask botania to remove that compatibility patch until railcraft is fully ready for mc 1.12.

**Comment by liach** [comment]
@Generalcamo did botania remove that compat?

**Comment by Generalcamo** [comment]
No but the issue is they haven't updated the API. That's not our problem. It's the CartItem class that was updated to use BlockPos rather than three ints that they need to update
