### ISSUE TITLE
Start to use Access Transformers

### ISSUE THREAD

**Issue by liach** [Railcraft/Railcraft#1418]

**Comment by Dockter** [comment]
This will solve a lot of guessing especially with random numbers being used to determine numeric field values in classes.

**Comment by Speiger** [comment]
@liach before you access transform everything that isnt public yet please check if these variables are accessebile without reflection in the first place in the newer version, because CJ was terrible at checking those kind of things later on, (I reported already a couple of these issue because of that).
I dont mean also to offend you or CJ by that, its just the case, if someone would not report it CJ would still use reflection to access the Midmapping settings.

**Comment by liach** [comment]
@speiger my forge pr had fixed that. sometimes i AT because of side limitations.
