### ISSUE TITLE
Server crash - LootConditionManager

### ISSUE THREAD

**Issue by ProsperCraft** [Railcraft/Railcraft#1770]
**Description of the Bug**

Server crashed when two players on mining, guessing worldgen.

**Logs & Environment**

 - Full log: [2019-03-10-7.log.gz](https://github.com/Railcraft/Railcraft/files/2951095/2019-03-10-7.log.gz)

 - Crash report (If available): https://gist.github.com/ProsperCraft/13657c0245690a506666e51fa1ca9831

**Additional context**
Modpack - https://minecraft.curseforge.com/projects/drtardis-2-new-adventures

**Comment by liach** [comment]
looks weird. might be loot table set in the cart related, i guess? don't have mappings available so not sure.

**Comment by liach** [comment]
Hmm, turns out that a sneaky mod that adds a null loot pool is the culprit.
https://paste.fedoraproject.org/paste/oKNoistx~PNbBWuSHlvnRw
Unfortunately, I cannot help you identify which specific mod is breaking all these. Thank you for your cooperation! Feel free to report more issues and ask for help if you have another problem with Railcraft!
