### ISSUE TITLE
Rock Crusher issue

### ISSUE THREAD

**Issue by Solverbolt** [Railcraft/Railcraft#1780]
**Description of the Bug**

Built the rock crusher, as I have done for 6 years now, and while the multiblock forms, its showing a new window in the center, "network usage: 100%" It is also not accepting power of any kind, from anything. 
Modpack: FTB Ultimate Reloaded Version 1.0.1
Minecraft Version 1.12.2

**To Reproduce**

1. Place block/cart Build Rock Crusher, attempt to connect power to it. 
2. Click on Open gui, and look
3. See It forms, but does not work

**Expected behavior**

I expected it to receive power from Thermal Expansions Fluxduct, or any of the dynamos, it does not
**Screenshots & Video**

![2019-03-13_23 50 44](https://user-images.githubusercontent.com/38087746/54337058-f6652b80-45ea-11e9-8bb8-6cd10eb477dc.png)
![2019-03-13_23 47 14](https://user-images.githubusercontent.com/38087746/54337063-f8c78580-45ea-11e9-9a6e-eed0516c07df.png)

**Logs & Environment**

 - Full log: 

 - Crash report (If available): 

**Additional context**

**Comment by liach** [comment]
Uh, it uses Railcraft charge.

**Comment by CovertJaguar** [comment]
Put a Flux Transformer between it and your conduits.

**Comment by Solverbolt** [comment]
actually, Its not Accepting ANY power, because the twit behind the modpack removed all your railcraft engine power sources.

**Comment by Solverbolt** [comment]
and the flux transformers do not craft either

**Comment by Solverbolt** [comment]
but if you want to ignore it like everything else, and try to shift the blame to someone else, be my guest, it just shows how weak and cowardly this group has become in the last few years

**Comment by CovertJaguar** [comment]
I have no idea who you are directing that to, but please try to remain civil. 

Railcraft provides the means to power its machines using Charge. We even provide the means to make Charge from FE, though admittedly the Flux Transformer is probably broken in Beta-5. Its fixed in rc-1 and will be fixed in the stable release.

If you are running a mod pack that removes the necessary bits, there isn't really anything we can do about it. You need the Flux Transform for FE to Charge or the IC2 Feeder for EU to Charge. Or you need to run a Boiler/Turbine setup. Charge is transmitted with Shunting Wires.

We decided that the best route for Railcraft was to distance ourselves from other power systems and implement our own. This gives us more control and simplifies the code a lot. None of the other power systems were suitable for the technical requirements of powering world spanning electric railways, at least not without bringing your computer to its knees.
