### ISSUE TITLE
iron/steel tank cart

### ISSUE THREAD

**Issue by WarlordWossman** [Railcraft/Railcraft#1787]
**Is your feature request related to a problem? Please describe.**
Not really a problem but it would help modpacks with progression.

**Describe the solution you'd like**
Instead of just having the tank cart there would be 2 tank carts (iron and steel) matching the tiers of the multiblock tanks from RC, the recipe for the steel tank cart would use a steel tank gauge instead of the iron one.
Capacity would be double of the configured size for the normal (iron) tank cart to stay consistent with the config for iron tanks.

**Additional context**
Having the option for a more expensive tank cart that can hold twice as much might come in handy if you need to transport a lot of fluids as you need less carts (less lag).
Sure I could configure the tank cart to just hold a lot of fluid but that would be an "all or nothing" situation, with 2 tiered tank carts I can hand one out earlygame and keep the bigger one for later when people want to transport way more liquids so they don't have to spam small tank carts.

As a coding noob I imagine it could almost be a copy of the code for the already existing tank cart and the textures could just use the colors for iron and steel instead of the default red texture.

**Comment by liach** [comment]
our current tank cart already takes an iron tank gauge for its recipe. a "steel tank cart" is possible, though we need to find out what its drag, etc. should be.

**Comment by WarlordWossman** [comment]
>our current tank cart already takes an iron tank gauge for its recipe

yeah that's what I was refering to when I said the suggested one could use the steel tank gauge.
the drag of the current tank cart doesn't scale with the volume of the liquid inside the tank right?

**Comment by CovertJaguar** [comment]
It does not.

**Comment by WarlordWossman** [comment]
With different cart size the fluid could honestly be added to a base drag value but it really depends how you guys want it to be from a design standpoint. It could be confusing if you test stuff that works with empty carts and doesn't with filled ones anymore.
Otherwise could just go with 1,5 times the drag since the bigger tank cart should be a little better since it needs higher tier materials to make in the first place.

**Comment by liach** [comment]
@CovertJaguar Opinions on whether to add this?

**Comment by CovertJaguar** [comment]
People don't really like trains with different speeds for some reason. I assume its mostly due to poor signalling on their railways. So I'm torn on the speed limiter. On one hand, it would make the battery cart increased drag less unique. On the other I'm not sure if it actually adds anything gameplay wise. If we did, we'd probably need a new, better system for calculating speed limits than what the battery carts use now.

As for the Iron/Steel Tank carts, I think its unnecessary. I don't like tiers. No one will ever use the Iron Tank Carts, ever. It kind of works for the big tanks because of the resource investment and the big tanks being overkill for most uses, but I don't see the same situation existing with the tank cart.

If it doesn't add an interesting choice, it shouldn't be in the game in my opinion.

I can see why it might be interesting from a modpack/map perspective though. But that's a pretty narrow use case.
