### ISSUE TITLE
Enhancement: allow water tanks to use same dimensions as your other multiblock tanks. 

### ISSUE THREAD

**Issue by mikeloeven** [Railcraft/Railcraft#181]
I have a base that uses a lot of water and i decided to try out the rain tank as a functional aesthetic. the thing is that the 3x3x3 version is neither big enough nor does it generate fast enough for my needs. and instead of using 3 or 4 of them i would like to be able to simply make one large one similar in dimensions to the large iron tanks which would meet my needs a bit better i am actually surprised that this item doesn't already have multiple supported dimensions.

**Comment by CovertJaguar** [comment]
If this becomes a thing, it should fill the interior with water similar to how the Blast Furnace fills with Water.

**Comment by wshadow** [comment]
Just a heads up: I'm taking a shot at this. Anyone want to talk to me about it, either here or ping me on IRC (name is daniel there). My code will be in branch watertankissue181.

**Comment by Vexatos** [comment]
@CovertJaguar Some mods make water finite, and there are cheaty ways to extract water from inside the multiblock, so care needs to be taken.

**Comment by liach** [comment]
It seems that the lava core of blast furnace is flowing lava, so CovertJaguar could make a flowing water core for it.

**Comment by Vexatos** [comment]
Indeed. He just needed to make sure they don't create source blocks.

**Comment by Taschenmogul** [comment]
Ok, this suggestion is a little bold, but after having thought about it for a while I decided to just propose this without further introduction:

Scrap the concept of the water tank as a standalone device and in it's place, using it's textures, introduce a "wooden tank" as a low-cost low-capacity alternative to iron and steel tanks that also fits in well with the pseudo-medieval flair of vanilla minecraft.
As a replacement for the water tank add "rain drain" blocks to all of the now three tanks that, if put in the top layer of a tank, will make the tank produce water as the water tank does now.
Installing more of them would mean faster water production which would mean that increasing the tank diameter would enable you to generate more water per tick while increasing tank height or using another tank material would only increase tank capacity.

I know this completely blows the scope of the original proposal, so scold me if you want, but I do believe that this might ultimately be the most useful solution; enabling players to use the water tank aesthetics in many more cases while making water generation in Railcraft more powerful and flexible.

**Comment by CovertJaguar** [comment]
It's not a bad idea.

**Comment by viliml** [comment]
The only problem is that doing so would require 2 more metadata values in the "beta" machine block (for the iron and steel "rain drains"), which is full.
Moving 2 blocks (best choice would be the void and metal chests) would fix that but cause world corruption, so it should be done in the 1.8 update, if ever.

**Comment by CovertJaguar** [comment]
Well it doesn't have to have those blocks.

**Comment by viliml** [comment]
So, only the new wooden tank multiblock will have rain drains, not the iron and steel ones?

**Comment by wshadow** [comment]
Another thing I was just thinking about. If we do re-purpose the water tank to be a lower tier tank, should it be able to hold any liquid or still just water? Lava (or molten metals, etc.) don't seem to make sense in a wooden tank...

**Comment by Taschenmogul** [comment]
I see how storing lava in a wooden tank can annoy some people by breaking their immersion.
On the other hand quite some other popular mods don't impose restrictions that are so strictly rooted in real-world logic and doing that for the wooden tanks would certainly annoy another group of people.

So, as doing it either way could annoy players, I believe that a config option to choose whether or not to keep wooden tanks from storing certain liquids might be the best thing.

**Comment by Landrash** [comment]
Spent a few hours looking at the code Railcraft and the tanks to be more precise.
A rewrite is possible but a few goals should probably be set.

Here's what I suggest.

1.The handler for the Tanks are rewritten to a general tank handler. As it is now its called MetalTank. I suggest its renamed to something more general. 

2. New tanks are implemented to replace the normal water tank. New tanks as previously suggested are the wood tank and I would suggest adding brick and stone tanks to that list.

3. To combat the problem with loosing the water generating ability of the wood tank I suggest the addition of a 3x3x1 multiblock called the Rain collector that can be added on top of whatever tank the player wants. This should not be an extension of the tank but rather a separate multiblock. Either connect it with pipes to the tank or have it auto eject water down trough the middle block.  

4. The new tanks should probably have a smaller capacity.  

5. Suggestion would be that since the new tanks are made from more common simpler materials that they are prone to leaks, a constant small drain of the contents.

6.The new tanks could not have any Gauge blocks as to give the Iron/Steel tanks another positive.

7. Since there's a almost infinite amount of mods adding different liquids some will more or less sense to have in for example a wooden tank. Either we try to have a infinite expanding whitelist/blacklist of tanks vs liquids or we have a lore option of using "Treated Wood " that's fire retardant. Combining a plank with a bucket of creosote Oil (ignoring realism) could wield a treated plank for use in the new tank. This used with the current Water Tank recipe that uses a slimeball for "Waterproofing" should be lore friendly enough in my mind.  

Thoughts or ideas?

**Comment by Generalcamo** [comment]
Any updates regarding this?

**Comment by liach** [comment]
Waiting till 10.2

**Comment by liach** [comment]
@Generalcamo Dunno if we would add this feature. Water tank is much cheaper than iron/steel tanks and I fear this addition may be unfair.

**Comment by mikeloeven** [comment]
Not really TBH water is a infinite regenerative resource there is really no balance issue here especially since most of the mod packs including RC also have other mods with water collection devices. Honestly I ended up just building a water tank for aesthetics and sticking an Aqueous accumulator inside it with some water blocks.

**Comment by Generalcamo** [comment]
@liach I had planned to make it more expensive (sort-of), removing the requirement for Slime but requiring bronze plating and creosote blocks.

**Comment by liach** [comment]
I strongly agree. I will assign this to you.

**Comment by Generalcamo** [comment]
This issue has a lot of complicated ideas being put forward, with no clear direction on exactly what should be done. This is going to need some brainstorming on what exactly should be done. I'm almost tempted to close this issue and just make a new one.

Of course I have my own ideas on the implementation, but they involve a potentially controversial rework to the water tank.

**Comment by CovertJaguar** [comment]
Well here's an idea that got completely forgotten.
