### ISSUE TITLE
No Engines implemented

### ISSUE THREAD

**Issue by Legondas** [Railcraft/Railcraft#1840]
Folowing problem. I have a Minecraft 1.12.2 Server with Railcraft and many other mods installed and I can't craft the Steam Engines. They are not even in the JEI interface. Is there maybe some incompatibility with another mod? I've tested it Singleplayer and have the same Problem.

The mods are the following:

BiblioCraft[v2.4.5][MC1.12.2].jar
BiomesOPlenty-1.12.2-7.0.1.2438-universal.jar
Carpenter's Blocks v3.4.0-poc.5 - MC 1.12.2.jar
Chameleon-1.12-4.1.3.jar
Chisel-MC1.12.2-0.2.1.35.jar
Decocraft-2.6.2_1.12.2.jar 
DrZharks MoCreatures Mod-12.0.5.jar
EnchantingPlus-1.12.2-5.0.176.jar
Farseek-1.12-2.3.1.jar
forgeessentials-1.12.2-12.3.56-server.jar
GardenStuff-1.12-2.1.1.jar
GraveStone-1.12.2-Graves-1.3.1.jar
HungerOverhaul-1.12.2-1.3.3.jenkins148.jar
Hwyla-1.8.26-B41_1.12.2.jar
ImmersiveEngineering-0.12-89.jar
InventoryTweaks-1.63.jar
jei_1.12.2-4.15.0.268.jar
journeymap-1.12.2-5.5.5b5.jar
malisisdoors-1.12.2-7.3.0.jar
mystcraft-1.12.2-0.13.7.03.jar
NoMoreRecipeConflict-0.13(1.12.2).jar
OpenBlocks-1.12.2-1.8.jar
OptiFine_1.12.2_HD_U_E3.jar
oreberries-1.12.x-0.5.0.jar
OreDictionaryConverter-1.11.0.jar
Pam's+HarvestCraft+1.12.2zc+The+7mm+Kidney+Stone+Update.jar
Plants-1.12.2-2.10.7.jar
railcraft-12.0.0.jar
redstonepaste-mc1.12-1.7.5.jar
Ruins-1.12.2.jar
secretroomsmod-1.12.2-5.6.4.jar 
Streams-1.12-0.4.4.jar
TConstruct-1.12.2-2.12.0.135.jar
Thaumcraft-1.12.2-6.1.BETA26.jar
 ThaumicAdditions-1.12.2-13r.jar
ThaumicInventoryScanning_1.12.2-2.0.10.jar
ThaumicJEI-1.12.2-1.5.6-24.jar
Tree-Chopper-Mod-1.12.2.jar
Wawla-1.12.2-2.5.271.jar
WearableBackpacks-1.12.2-3.1.3.jar
worldedit-forge-mc1.12-6.1.8-dist.jar

I really want to use the Engines, so if anyone has an idea I would be glad

thanks
Legondas

**Comment by Legondas** [comment]
Just tried to do a Clean install with only Railcraft installed. Same thing. Are the Engines removed?

**Comment by LuigiHutch** [comment]
https://github.com/Railcraft/Railcraft/issues/1388

**Comment by Legondas** [comment]
K didn't see that post. Thanks

**Comment by super-sswell** [comment]
Not sure why this was closed, this is still a problem in:
FTB Revelation version 3.2.0 for minecraft 1.12.2
Railcraft version 12.0.0
As of June 2020

**Comment by Polar-Phoenix** [comment]
> Not sure why this was closed, this is still a problem in:
> FTB Revelation version 3.2.0 for minecraft 1.12.2
> Railcraft version 12.0.0
> As of June 2020

Watch for issue #1388 , in nutshell : API for MJ-producing engines unstable right now, so there will be no engines in mod until stable API in Buildcraft is made.

**Comment by Raptor22a** [comment]
> 

A few months over a year later... any word?

**Comment by gatoborrachon** [comment]
@Raptor22a Check this: https://github.com/Railcraft/Railcraft/pull/2000

**Comment by Raptor22a** [comment]
> @Raptor22a Check this: #2000

The last action that I see on #2000 besides you mentioning it was 12 months ago with @Su5eD adding 4 commits to it. It says all checks have passed but merging is blocked - which makes sense, since I'm not added to the project (not that I'd be able to do much with it even if I did; I only have just over surface-level info on how minecraft mods work). It's still listed as open, so I'm guessing that there's either some issue with re-implementing the engines that's holding it up, or it simply hasn't been worked on (judging by the last commit being a year ago, I'm guessing the latter)

The last public update (that I can at least find) on sites like CurseForge was nearly _three years ago_ in March of 2019.  There's no released on GitHub, so the only other thing that I could think of is trying to download the master repository and compile it myself (which would involve figuring out how to compile a minecraft mod in the first place - I believe I have all the right java packages and creator content, etc., but it's just a matter of doing a bunch of reading).
So, right now I'm at a loss I guess.

**Comment by Su5eD** [comment]
From what I remember that PR is done, and is currently waiting for CJ or someone else to review it, although I'm not sure if it's still worth updating 1.12

**Comment by Raptor22a** [comment]
> From what I remember that PR is done, and is currently waiting for CJ or someone else to review it, although I'm not sure if it's still worth updating 1.12

Well, how much work would it take to add in? I mean, if it's pretty much done except for review, I don't see why it shouldn't be wrapped up finally. I'd love to be able to use this stuff in 1.12.2, because other than the steam turbine and steam oven, there's really no use for the railcraft boilers in 1.12.2 otherwise.

**Comment by gatoborrachon** [comment]
he wants to finish something, i could remember it was about Multiblocks, but yeah, i also can't wait for the new update, some bugs fixed, new content, etc.

Also, how that there's not other use? Using steam to produce MJ will come handy, but right now using Steam to produce EU/RF/Charge (in the Steam Turbine) is a vital part of a classic modded minecraft instance (or at least in my modpack)

**Comment by Raptor22a** [comment]
> he wants to finish something, i could remember it was about Multiblocks, but yeah, i also can't wait for the new update, some bugs fixed, new content, etc.
> 
> Also, how that there's not other use? Using steam to produce MJ will come handy, but right now using Steam to produce EU/RF/Charge (in the Steam Turbine) is a vital part of a classic modded minecraft instance (or at least in my modpack)

Well, the steam turbine is useful for generating power, but not in compact spaces. It's quite a large multi-block structure, and in things such as airships (using Valkyrien Skies - how I adore that mod!), space is at a premium. It'd be nice to use smaller engines to get things done without having to take up as much of the precious small space on the ship as a large turbine setup.

**Comment by gatoborrachon** [comment]
I also like ValkyrienSkies, i only tested it with some IC2 Machines, does multiblocks work too? (specially [Railcraft multiblocks](https://github.com/Railcraft/Railcraft/issues/1996), the previous issue happens too with the Coke Ovens)

And yeah, maybe the free space in a VS Ship can be spend so quickly specially with big multiblocks, but for that you could make a bigger ship, i remember a video in r/feedthebeast about a japanese ambiented ship, it was beautiful, although i can't find it again, but this is a pretty well example of a Big Ship:
https://www.youtube.com/watch?v=OHnP8PGsvxI

Now imagine one of these inside it: 
![boiler_screenshot](https://user-images.githubusercontent.com/61126174/150557120-a34db912-e305-4760-99c2-3b0cbcc0e8eb.jpg)

![turbine_screenshot](https://user-images.githubusercontent.com/61126174/150557572-ba989a7a-d9e7-44a7-bee7-c876dcfb62ec.jpg)
-Pics obtained from [here](https://railcraft.info/wiki/device:steam_boiler) and [here](https://railcraft.info/wiki/device:steam_turbine)
