### ISSUE TITLE
How about at least allowing me to use the base game rail system which actually makes sense?

### ISSUE THREAD

**Issue by ortund** [Railcraft/Railcraft#1870]
Your wiki doesn't explain how to make anything.
Your wiki doesn't explain how to use the crap you've crowbarred into the game

and I don't even know whether or not it'll suit my build IF I ever figure out how to fucking use it in the first place.

My build was fine with the base game components. Why the hell would you take them out?

**Comment by texaswriter** [comment]
You installed a mod without backing up your world or understanding the affects of the mod? This is a problem of the mod author or you? 

Otherwise, you are using expletives towards somebody who voluntarily makes a mod for you to enjoy (which is also voluntary). Consider acting like you are older than 8 years old. 

Otherwise, JEI is your friend. I'm sure you can do EXACTLY the same thing with the new blocks. I've been able to figure everything out on the [WIKI](http://railcraft.info/wiki/start), using the IN-GAME TOOLTIPS, and with online videos (try searching for railcraft <your search term> on google or youtube for lots of great info). But whatever you do, PLEASE, AGAIN,  **consider acting like you are older than 8 years old.**

**Comment by ortund** [comment]
> You installed a mod without backing up your world or understanding the affects of the mod? This is a problem of the mod author or you?

I installed mod pack which had the mod in it (I didn't go through all 140+ mods in the pack, forgive me my egregious oversight).

> Otherwise, you are using expletives towards somebody who voluntarily makes a mod for you to enjoy (which is also voluntary). Consider acting like you are older than 8 years old.

Consider watching your fucking mouth or fucking yourself with a rusty meat cleaver.

> Otherwise, JEI is your friend. I'm sure you can do EXACTLY the same thing with the new blocks. I've been able to figure everything out on the [WIKI](http://railcraft.info/wiki/start), using the IN-GAME TOOLTIPS, and with online videos (try searching for railcraft on google or youtube for lots of great info). But whatever you do, PLEASE, AGAIN, **consider acting like you are older than 8 years old.**

The version of JEI I've got isn't updated for this bullshit so the recipes it gives me are retarded. Thanks for the help... I don't know what I'd do without you.
