### ISSUE TITLE
Poor Gold

### ISSUE THREAD

**Issue by Notlucky101** [Railcraft/Railcraft#1900]
Even thought ore_metal_poor_gold is disabled still spawns.

**Comment by FLAPIXCODE** [comment]
In RailCraft, everything is very bad with ore generation. Therefore, in the normal way, it cannot be turned off in any way (voids appear or does not turn off at all).
But i found a solution: go to the "config / railcraft / ores" folder. This is the folder with the settings for generating all ores. Open the file "mine_gold.cfg". We are interested in two lines (CTRL + F):
`S:core=minecraft:gold_ore#0`
`S:fringe=railcraft:ore_metal_poor#1`
"core" is the main ore (in this case, it repeats the original minecraft gold ore, but is generated by the mod itself).
"fringe" is bad ore. Since it is impossible to disable it in the normal way, we just change it to a regular stone, and it turns out like this:
`S:fringe=minecraft:stone`
In general, this way you can turn off all metal ores in this folder (both basic and bad) if they are not needed (for example, IC2 is installed, and it generates copper, tin, etc.), and this will not cause any problems.

**Comment by FLAPIXCODE** [comment]
> In RailCraft, everything is very bad with ore generation. Therefore, in the normal way, it cannot be turned off in any way (voids appear or does not turn off at all).
> But i found a solution: go to the "config / railcraft / ores" folder. This is the folder with the settings for generating all ores. Open the file "mine_gold.cfg". We are interested in two lines (CTRL + F):
> `S:core=minecraft:gold_ore#0`
> `S:fringe=railcraft:ore_metal_poor#1`
> "core" is the main ore (in this case, it repeats the original minecraft gold ore, but is generated by the mod itself).
> "fringe" is bad ore. Since it is impossible to disable it in the normal way, we just change it to a regular stone, and it turns out like this:
> `S:fringe=minecraft:stone`
> In general, this way you can turn off all metal ores in this folder (both basic and bad) if they are not needed (for example, IC2 is installed, and it generates copper, tin, etc.), and this will not cause any problems.

I finally figured out how to do it right.
If you need to completely remove all ore: either delete the file with the ore config, or open it and delete 0 from the "dimensionWhitelist" block, then add it to "dimensionBlacklist".
And to remove poor ore, you need to do this (at the very bottom of the config):
`S:coreOre=1.0`
`S:fringeGen=0.0`

**Comment by CovertJaguar** [comment]
The generators are built from the config files. Delete the file, no generation.
