### ISSUE TITLE
Support for Buildcraft Energy fuels (Dense / Light / Gaseous) in the Steam Boiler?

### ISSUE THREAD

**Issue by StevenMichaelC** [Railcraft/Railcraft#2032]
The steam boiler has always been my favorite energy system, but the "Buildcraft Energy" mod present in some modpacks revamps the oil refining process, replacing default buildcraft fuel with 3 fuels separated from each other with a heat-exchanging refinery system. As such, any oil wells found in the world are far less useful than they used to be.

It would be nice to be able to use these refined fuels in the boiler, but the Liquid Firebox doesn't accept it being piped in, or by bucket. It works with creosote, but that is far more tedious to keep a steady supply of. I tried using these fuels last year, and again yesterday. But it still doesn't work.

For reference, I play using the FTB Revelations modpack.

**Comment by gatoborrachon** [comment]
If i recall correctly, BuildCraft Fuels compat was added in one of these updates between 2019 and 2021, but we know that there was not any new release since 2019, so even if they were added (or not), you can use [MoreTweaker](https://www.curseforge.com/minecraft/mc-mods/moretweaker) to [add these fuels by yourself](https://bitbucket.org/noeppi_noeppi/moretweaker/wiki/Railcraft.md), although the only issue left is that you will require to check the balance

**Comment by CovertJaguar** [comment]
Done

**Comment by gatoborrachon** [comment]
nice, thank you
