### ISSUE TITLE
Crash with Cart with Standard Worldspike

### ISSUE THREAD

**Issue by michelegargiulo** [Railcraft/Railcraft#2052]
Game crashes as soon as a train (Steve's carts cart -- minecart -- chest cart -- standard worldspike cart) went out of player-loaded chunks. Game now crashes on world load with the same exact error.

When the issue happened, worldspikes were set to not require any fuel. Enabling fuel requirements and reloading the world still results in the same crash.

Logs, crash report and config file:
https://gist.github.com/michelegargiulo/4cc2c1cf8e2624be5bf46d9e439c1fdd

Please let me know if anything else is needed, I can provide additional logs and world download.

**Comment by CovertJaguar** [comment]
Okay, one comment.

The config for the worldspikes has moved to the worldspike.cfg module file in the modules folder. So you weren't actually disabling the fuel requirement.

If you had modified it in the correct place, it probably wouldn't crash.

The crash is probably due to some changes I made to the cart hierarchy. Will fix.
