### ISSUE TITLE
идеи для RailCraft

### ISSUE THREAD

**Issue by director777-moderator** [Railcraft/Railcraft#2063]
:)

**Comment by director777-moderator** [comment]
Привет, Covert_Jaguar. Ты знаешь меня в Discord.
У меня есть много идей для мода RailCraft.

**Comment by director777-moderator** [comment]
Если тебе интересно, напиши + пожалуйста

**Comment by director777-moderator** [comment]
> _No descriptio

**Comment by director777-moderator** [comment]
Часть 1- локомотивы:
в мод стоить добавить несколько новых локомотивов.
Их можно скрафтить если установлены некоторые другие моды.
1) тепловоз( крафтится когда установлен Buildcraft)
![2022-07-20_14 47 50](https://user-images.githubusercontent.com/109589885/179999297-4c7489e4-42e8-493c-b926-999999ffe880.png)
(крафт тепловоза)
может ездить на реверсе на 2 скорости.
Ему нужно топливо из Buildcraft

**Comment by director777-moderator** [comment]
2)Газотурбовоз (крафтится когда установлен GregTech Community Edition)
![2022-07-20_14 52 40](https://user-images.githubusercontent.com/109589885/179999942-ee75175d-6bfc-47d6-b5ad-4b7439b38f4f.png)
может ездить на реверсе на 4 скорости.Ему нужен любой газ из GregTech Community Edition.

**Comment by director777-moderator** [comment]
Ну как тебе?

**Comment by Forecaster** [comment]
A diesel locomotive is already planned. See #651.

A gas turbine locomotive probably wont be added into Railcraft since there are no plans for gasses other than steam at this time. Such a thing would probably be better added by the relevant mod, or by a small addon, using the Railcraft API.

In general Railcraft tries to be self-sufficient in that everything it adds is usable even if no other mods are installed. This isn't universally true as there are some blocks that aren't useful in those cases, but for things like locomotives this rule is kept.

When creating tickets here it's preferable if you search existing tickets first to see if the issue has been brought up and closed before. Make sure to include closed tickets in the search.

The main text of the issue should contain a description of, in this case, the suggestion and relevant images and such. Beginning a ticket only with ":)" is not great. Tickets are also not meant for posting comments like "How are you?". Try to keep comments relevant to the topic of the ticket.

**Comment by director777-moderator** [comment]
2 часть- рельсы: 
1. Монорельсовый путь
Быстрее усиленного но медленнее высокоскоростного. Крафтится из. 3 железных блоков в прокатном стане.
2. Подвесной путь
Путь который ставится не на блок а на нижнюю грань блока. Может висеть без опоры 9 блоков. Крафтится из ускоряющего пути и 3 железных столбов.
