### ISSUE TITLE
Hobbyist steam engine can be connected to wooden transport pipes

### ISSUE THREAD

**Issue by nightovl** [Railcraft/Railcraft#2070]
Forge version:14.23.4.2860
Railcraft version:12.1.0-beta-8

**Comment by jackisgood99** [comment]
i would assume this isnt a bug as the hobbyist steam engine would have an internal inventory for fuel

**Comment by gatoborrachon** [comment]
i mean, yeah, the Hobbyist Steam Engine has an inventory slot, it would make total sense to be able to connect transport pipes to it

I can only think that MAYBE his issue is that the wooden transport pipe is able to connect to the Steam Engine in the face where the power i supposed to get out (i have zero proof), that would be a small bug and actually quite insignificant (since you can use the Buildcraft Wrench to fix this), but since Night0v0 have not uploaded pics of this "supposed" event, i can't stand with him
