### ISSUE TITLE
Steam turbine housing not working with AE buses

### ISSUE THREAD

**Issue by ITFactoryAUT** [Railcraft/Railcraft#219]
It is not working to exchange the rotors of a steam turbine housing with any pipes, AE import and export buses or any other stuff.
Could you please fix that?

**Comment by Potato-Matic** [comment]
@CovertJaguar 

That may be true, but your beta testers are a small group and may not necessarily be representative of the community which uses Railcraft, in all of the varied modpacks and cases. As a casual player who's run into this issue before, I've seen a lot of threads and issues opened on this issue and I'm sure you've seen even more. I think it's far more than evident by now that a significant portion of Railcraft's userbase have found that it's a design decision that has had a strong negative influence on their enjoyment of the mod, especially considering the turbine's otherwise well-placed role as a unifier of the Buildcraft and Industrial Craft energy systems.

I'm not asking for the method to be an easy or cheap one, and I'm not asking for it to be enabled by default, but I think it's fairly reasonable to request that the option be available for people who want to set up a system to exchange (or even just repair) turbine rotors.

Considering the amazing work that's been done on multiblock structures in Railcraft, one suggestion I have would be to require that the turbine be completely shut down, and considering it's a two by two by three block structure, require that a rotor disk be removed and replaced in each of the four-block slices. Replacement could also require additional resources (like lubricant) or it might only be possible using specially set carts from above (sort of acting like an overhead crane on its rails). This whole operation could even require coordination using buildcraft gates (provided they are installed) which command and coordinate each step during the procedure, as a foreman and deck hands would.

This is all just a mixed bag of suggestions that I can put forth on how replacement might be done in a narratively-consistent manner. I hope that you might see my reasoning in suggesting this change, and might find some of these suggestions inspiring.

-Matt

**Comment by liach** [comment]
1.7.10 is done. this feature won't come.

**Comment by Potato-Matic** [comment]
@liach What do you mean 1.7.10? I'm not referencing a particular version, and as far as I know Railcraft is still being actively developed and supported.

Are you speaking from experience, or are you someone on the Railcraft development team? The beta testers?

**Comment by liach** [comment]
in 1.10.2, the steam turbine is not back yet. if ae pipes don't work with other inventory machines, open a new issue instead.
